module.exports = {
	_object: '/api/response',
	self:
		'https://api.flexport.com/ocean/shipment_containers?f.shipment.id=542526',
	version: 2,
	data: {
		_object: '/api/collections/paginated',
		prev: null,
		next: null,
		total_count: 1,
		data: [
			{
				metadata: {},
				_object: '/ocean/shipment_container',
				id: 258347,
				container_type: 'dry',
				container_number: 'NYKU3679213',
				container_size: 'twenty_ft',
				seal_number: 'S123456',
				estimated_departure_date: '2019-09-01T12:00:00.000+08:00',
				actual_departure_date: null,
				estimated_arrival_date: '2019-09-25T12:00:00.000-07:00',
				actual_arrival_date: null,
				estimated_pickup_date: '2019-08-29T12:00:00.000+08:00',
				actual_pickup_date: null,
				estimated_delivery_date: null,
				actual_delivery_date: null,
				last_free_day_date: null,
				empty_returned_date: null,
				cargo_ready_date: '2019-05-25',
				available_for_pickup_date: null,
				estimated_available_for_pickup_date: null,
				shipment: {
					_object: '/api/refs/object',
					ref_type: '/shipment',
					link: 'https://api.flexport.com/shipments/542526',
					id: 542526,
				},
				container_legs: {
					_object: '/api/refs/collection',
					ref_type: '/ocean/shipment_container_leg',
					link:
						'https://api.flexport.com/ocean/shipment_container_legs?f.shipment_container.id=258347',
				},
				items: [],
			},
		],
	},
	error: null,
}
