module.exports = {
	_object: '/api/response',
	self:
		'https://api.flexport.com/ocean/shipment_containers?f.shipment.id=663832',
	version: 2,
	data: {
		_object: '/api/collections/paginated',
		prev: null,
		next: null,
		total_count: 1,
		data: [
			{
				metadata: {},
				_object: '/ocean/shipment_container',
				id: 300710,
				container_type: 'dry',
				container_number: 'KKFU7884874',
				container_size: 'fourty_ft_hc',
				seal_number: '',
				estimated_departure_date: '2019-11-08T12:00:00.000+08:00',
				actual_departure_date: null,
				estimated_arrival_date: '2019-11-29T12:00:00.000-08:00',
				actual_arrival_date: null,
				estimated_pickup_date: null,
				actual_pickup_date: null,
				estimated_delivery_date: '2020-01-06T12:00:00.000-08:00',
				actual_delivery_date: null,
				last_free_day_date: null,
				empty_returned_date: null,
				cargo_ready_date: null,
				available_for_pickup_date: null,
				estimated_available_for_pickup_date: null,
				shipment: {
					_object: '/api/refs/object',
					ref_type: '/shipment',
					link: 'https://api.flexport.com/shipments/663832',
					id: 663832,
				},
				container_legs: {
					_object: '/api/refs/collection',
					ref_type: '/ocean/shipment_container_leg',
					link:
						'https://api.flexport.com/ocean/shipment_container_legs?f.shipment_container.id=300710',
				},
				items: [],
			},
		],
	},
	error: null,
}
