module.exports = {
	_object: '/api/response',
	self: 'https://api.flexport.com/shipment_legs?f.shipment.id=509792',
	version: 2,
	data: {
		_object: '/api/collections/paginated',
		prev: null,
		next: null,
		total_count: 5,
		data: [
			{
				_object: '/shipment_leg',
				id: 4219074,
				shipment: {
					_object: '/api/refs/object',
					ref_type: '/shipment',
					link: 'https://api.flexport.com/shipments/509792',
					id: 509792,
				},
				estimated_arrival_date: '2019-04-01T12:00:00.000+08:00',
				actual_arrival_date: null,
				estimated_departure_date: '2019-04-01T12:00:00.000+08:00',
				actual_departure_date: null,
				cargo_ready_date: '2019-04-01',
				additional_dates: {
					cargo_ready_date: '2019-04-01',
				},
				origin: {
					_object: '/shipment_node',
					tags: ['origin_address'],
					place: {
						_object: '/place',
						name: 'Factory X - Shenzhen Factory',
						address: {
							_object: '/address',
							street_address: '123 Table Street, TT Industrial Park',
							street_address2: null,
							city: 'Shenzhen',
							state: 'Guangdong',
							country: 'China',
							country_code: 'CN',
							zip: null,
							unlocode: null,
							timezone: 'Asia/Chongqing',
							ref: 'id-155975',
						},
						details: [],
					},
					terminal: null,
				},
				destination: {
					_object: '/shipment_node',
					tags: ['consolidation'],
					place: {
						_object: '/place',
						name: 'Flexport Hong Kong Warehouse',
						address: {
							_object: '/address',
							street_address:
								'Unit 153, 1/F, Airport Freight Forwarding Centre, 2 Chun Wan Road',
							street_address2: '香港新界离岛区骏运路2号，机场空运中心一楼153倉',
							city: 'Chek Lap Kok',
							state: null,
							country: 'Hong Kong',
							country_code: 'HK',
							zip: null,
							unlocode: 'HKHKG',
							timezone: 'Asia/Hong_Kong',
							ref: 'id-124613',
						},
						details: [],
					},
					terminal: null,
				},
				transportation_mode: 'truck',
				carrier_name: null,
				ocean_leg: null,
				air_leg: null,
				trucking_leg: {
					_object: '/trucking/shipment_leg',
					tracking_number: null,
					service_type: 'cartage',
					pieces: null,
					container_legs: null,
				},
				rail_leg: null,
			},
			{
				_object: '/shipment_leg',
				id: 4219075,
				shipment: {
					_object: '/api/refs/object',
					ref_type: '/shipment',
					link: 'https://api.flexport.com/shipments/509792',
					id: 509792,
				},
				estimated_arrival_date: '2019-04-03T12:00:00.000+08:00',
				actual_arrival_date: null,
				estimated_departure_date: '2019-04-03T12:00:00.000+08:00',
				actual_departure_date: null,
				cargo_ready_date: null,
				additional_dates: {},
				origin: {
					_object: '/shipment_node',
					tags: ['consolidation'],
					place: {
						_object: '/place',
						name: 'Flexport Hong Kong Warehouse',
						address: {
							_object: '/address',
							street_address:
								'Unit 153, 1/F, Airport Freight Forwarding Centre, 2 Chun Wan Road',
							street_address2: '香港新界离岛区骏运路2号，机场空运中心一楼153倉',
							city: 'Chek Lap Kok',
							state: null,
							country: 'Hong Kong',
							country_code: 'HK',
							zip: null,
							unlocode: 'HKHKG',
							timezone: 'Asia/Hong_Kong',
							ref: 'id-124613',
						},
						details: [],
					},
					terminal: null,
				},
				destination: {
					_object: '/shipment_node',
					tags: ['port_of_loading'],
					place: {
						_object: '/place',
						name: 'HKG - Hong Kong - Hong Kong',
						address: {
							_object: '/address',
							street_address: 'Hong Kong',
							street_address2: null,
							city: 'Hong Kong',
							state: null,
							country: 'Hong Kong',
							country_code: 'HK',
							zip: null,
							unlocode: 'HKHKG',
							timezone: 'Asia/Hong_Kong',
							ref: 'id-39800',
						},
						details: [
							{
								_object: '/air/port',
								port_code: null,
								iata_code: 'HKG',
								icao_code: 'VHHH',
							},
							{
								_object: '/trucking/port',
								port_code: null,
							},
						],
					},
					terminal: null,
				},
				transportation_mode: 'truck',
				carrier_name: null,
				ocean_leg: null,
				air_leg: null,
				trucking_leg: {
					_object: '/trucking/shipment_leg',
					tracking_number: null,
					service_type: 'cartage',
					pieces: null,
					container_legs: null,
				},
				rail_leg: null,
			},
			{
				_object: '/shipment_leg',
				id: 4219077,
				shipment: {
					_object: '/api/refs/object',
					ref_type: '/shipment',
					link: 'https://api.flexport.com/shipments/509792',
					id: 509792,
				},
				estimated_arrival_date: '2019-04-05T12:00:00.000-07:00',
				actual_arrival_date: null,
				estimated_departure_date: '2019-04-05T12:00:00.000-07:00',
				actual_departure_date: null,
				cargo_ready_date: null,
				additional_dates: {},
				origin: {
					_object: '/shipment_node',
					tags: ['port_of_unloading', 'customs_entry'],
					place: {
						_object: '/place',
						name: 'LAX - Los Angeles - CA',
						address: {
							_object: '/address',
							street_address: null,
							street_address2: null,
							city: 'Los Angeles',
							state: 'CA',
							country: 'United States',
							country_code: 'US',
							zip: '90045-5803',
							unlocode: 'USLAX',
							timezone: 'America/Los_Angeles',
							ref: 'id-41559',
						},
						details: [
							{
								_object: '/air/port',
								port_code: '2720',
								iata_code: 'LAX',
								icao_code: 'KLAX',
							},
							{
								_object: '/trucking/port',
								port_code: '2720',
							},
						],
					},
					terminal: {
						_object: '/shipment_node/terminal',
						name: 'CATHAY PACIFIC (IMPORT)',
						address: {
							_object: '/address',
							street_address: '5908 AVION DR',
							street_address2: null,
							city: 'LOS ANGELES',
							state: 'CA',
							country: 'United States',
							country_code: 'US',
							zip: '90045',
							unlocode: null,
							timezone: 'America/Los_Angeles',
							ref: 'id-71928',
						},
					},
				},
				destination: {
					_object: '/shipment_node',
					tags: ['destination_address'],
					place: {
						_object: '/place',
						name: 'Xavier LLC',
						address: {
							_object: '/address',
							street_address: '123 Main St, Los Angeles',
							street_address2: null,
							city: 'Los Angeles',
							state: 'CA',
							country: 'United States',
							country_code: 'US',
							zip: '90007',
							unlocode: null,
							timezone: 'America/Los_Angeles',
							ref: 'id-112580',
						},
						details: [],
					},
					terminal: null,
				},
				transportation_mode: 'truck',
				carrier_name: null,
				ocean_leg: null,
				air_leg: null,
				trucking_leg: {
					_object: '/trucking/shipment_leg',
					tracking_number: null,
					service_type: 'cartage',
					pieces: null,
					container_legs: null,
				},
				rail_leg: null,
			},
			{
				_object: '/shipment_leg',
				id: 6582973,
				shipment: {
					_object: '/api/refs/object',
					ref_type: '/shipment',
					link: 'https://api.flexport.com/shipments/509792',
					id: 509792,
				},
				estimated_arrival_date: '2020-02-27T15:20:00.000-09:00',
				actual_arrival_date: null,
				estimated_departure_date: '2020-02-27T22:50:00.000+08:00',
				actual_departure_date: null,
				cargo_ready_date: null,
				additional_dates: {},
				origin: {
					_object: '/shipment_node',
					tags: ['port_of_loading'],
					place: {
						_object: '/place',
						name: 'HKG - Hong Kong - Hong Kong',
						address: {
							_object: '/address',
							street_address: 'Hong Kong',
							street_address2: null,
							city: 'Hong Kong',
							state: null,
							country: 'Hong Kong',
							country_code: 'HK',
							zip: null,
							unlocode: 'HKHKG',
							timezone: 'Asia/Hong_Kong',
							ref: 'id-39800',
						},
						details: [
							{
								_object: '/air/port',
								port_code: null,
								iata_code: 'HKG',
								icao_code: 'VHHH',
							},
							{
								_object: '/trucking/port',
								port_code: null,
							},
						],
					},
					terminal: null,
				},
				destination: {
					_object: '/shipment_node',
					tags: [],
					place: {
						_object: '/place',
						name: 'ANC - Anchorage - AK',
						address: {
							_object: '/address',
							street_address: null,
							street_address2: null,
							city: 'Anchorage',
							state: 'AK',
							country: 'United States',
							country_code: 'US',
							zip: '99519-6960',
							unlocode: 'USANC',
							timezone: 'America/Anchorage',
							ref: 'id-41379',
						},
						details: [
							{
								_object: '/air/port',
								port_code: '3126',
								iata_code: 'ANC',
								icao_code: 'PANC',
							},
							{
								_object: '/trucking/port',
								port_code: '3126',
							},
						],
					},
					terminal: null,
				},
				transportation_mode: 'air',
				carrier_name: 'Cathay Pacific Airways',
				ocean_leg: null,
				air_leg: {
					_object: '/air/shipment_leg',
					iata_code: 'CX',
					icao_code: 'CPA',
					flight_number: 'CX 0096',
					pieces: null,
				},
				trucking_leg: null,
				rail_leg: null,
			},
			{
				_object: '/shipment_leg',
				id: 6582974,
				shipment: {
					_object: '/api/refs/object',
					ref_type: '/shipment',
					link: 'https://api.flexport.com/shipments/509792',
					id: 509792,
				},
				estimated_arrival_date: '2020-02-27T22:30:00.000-08:00',
				actual_arrival_date: null,
				estimated_departure_date: '2020-02-27T16:25:00.000-09:00',
				actual_departure_date: null,
				cargo_ready_date: null,
				additional_dates: {},
				origin: {
					_object: '/shipment_node',
					tags: [],
					place: {
						_object: '/place',
						name: 'ANC - Anchorage - AK',
						address: {
							_object: '/address',
							street_address: null,
							street_address2: null,
							city: 'Anchorage',
							state: 'AK',
							country: 'United States',
							country_code: 'US',
							zip: '99519-6960',
							unlocode: 'USANC',
							timezone: 'America/Anchorage',
							ref: 'id-41379',
						},
						details: [
							{
								_object: '/air/port',
								port_code: '3126',
								iata_code: 'ANC',
								icao_code: 'PANC',
							},
							{
								_object: '/trucking/port',
								port_code: '3126',
							},
						],
					},
					terminal: null,
				},
				destination: {
					_object: '/shipment_node',
					tags: ['port_of_unloading', 'customs_entry'],
					place: {
						_object: '/place',
						name: 'LAX - Los Angeles - CA',
						address: {
							_object: '/address',
							street_address: null,
							street_address2: null,
							city: 'Los Angeles',
							state: 'CA',
							country: 'United States',
							country_code: 'US',
							zip: '90045-5803',
							unlocode: 'USLAX',
							timezone: 'America/Los_Angeles',
							ref: 'id-41559',
						},
						details: [
							{
								_object: '/air/port',
								port_code: '2720',
								iata_code: 'LAX',
								icao_code: 'KLAX',
							},
							{
								_object: '/trucking/port',
								port_code: '2720',
							},
						],
					},
					terminal: {
						_object: '/shipment_node/terminal',
						name: 'CATHAY PACIFIC (IMPORT)',
						address: {
							_object: '/address',
							street_address: '5908 AVION DR',
							street_address2: null,
							city: 'LOS ANGELES',
							state: 'CA',
							country: 'United States',
							country_code: 'US',
							zip: '90045',
							unlocode: null,
							timezone: 'America/Los_Angeles',
							ref: 'id-71928',
						},
					},
				},
				transportation_mode: 'air',
				carrier_name: 'Cathay Pacific Airways',
				ocean_leg: null,
				air_leg: {
					_object: '/air/shipment_leg',
					iata_code: 'CX',
					icao_code: 'CPA',
					flight_number: 'CX 0096',
					pieces: null,
				},
				trucking_leg: null,
				rail_leg: null,
			},
		],
	},
	error: null,
}
