module.exports = {
	_object: '/api/response',
	self: 'https://flexport-sandbox.example.com/shipments?page=5&per=10',
	version: 2,
	data: {
		_object: '/api/collections/paginated',
		prev: 'https://flexport-sandbox.example.com/shipments?page=4&per=10',
		next: 'https://flexport-sandbox.example.com/shipments?page=6&per=10',
		total_count: 126,
		data: [
			{
				metadata: {},
				_object: '/shipment',
				id: 502170,
				name: 'LCL API TEST AWB#12345',
				booking: {
					_object: '/api/refs/object',
					ref_type: '/booking',
					link: 'https://api.flexport.com/bookings/81911',
					id: 81911,
				},
				transportation_mode: 'ocean',
				freight_type: 'door_to_door',
				incoterm: 'EXW',
				calculated_weight: {
					value: 1000,
					unit: 'kg',
					_object: '/quantity/weight',
				},
				calculated_volume: {
					value: 10,
					unit: 'cbm',
					_object: '/quantity/volume',
				},
				pieces: 234,
				it_number: null,
				created_date: '2019-03-09T14:24:40.655Z',
				status: 'in_transit_to_arrival_port',
				priority: 'standard',
				updated_at: '2020-03-04T12:29:27.831Z',
				archived_at: null,
				estimated_departure_date: '2019-03-18T12:00:00.000+08:00',
				actual_departure_date: '2019-03-18T12:00:00.000+08:00',
				estimated_arrival_date: '2019-03-29T12:00:00.000-05:00',
				actual_arrival_date: null,
				estimated_picked_up_in_full_date: '2019-03-14T12:00:00.000+08:00',
				actual_picked_up_in_full_date: '2019-03-14T12:00:00.000+08:00',
				estimated_delivered_in_full_date: '2019-04-19T12:00:00.000-07:00',
				actual_delivered_in_full_date: null,
				cargo_ready_date: '2019-02-27',
				air_shipment: null,
				ocean_shipment: {
					_object: '/ocean/shipment',
					is_lcl: true,
					house_bill_number: 'FSFESEW',
					master_bill_number: 'FWWEFW',
					carrier_booking_number: null,
					containers: {
						_object: '/api/refs/collection',
						ref_type: '/ocean/shipment_container',
						link:
							'https://api.flexport.com/ocean/shipment_containers?f.shipment.id=502170',
					},
				},
				shippers: [
					{
						_object: '/company_entity',
						id: 566428,
						name: 'Flexport Demo Shipper',
						mailing_address: {
							_object: '/address',
							street_address: '1 Queen St',
							street_address2: null,
							city: 'Causeway Bay',
							state: 'Hong Kong',
							country: 'Hong Kong',
							country_code: 'HK',
							zip: null,
							unlocode: null,
							timezone: 'Asia/Hong_Kong',
							ref: null,
						},
						ref: 'id-566428',
						vat_numbers: [],
					},
				],
				consignees: [
					{
						_object: '/company_entity',
						id: 556359,
						name: 'Bookings Test Consignee',
						mailing_address: {
							_object: '/address',
							street_address: '760 MARKET ST FL 8',
							street_address2: '',
							city: 'San Francisco',
							state: 'CA',
							country: 'United States',
							country_code: 'US',
							zip: '94102-2300',
							unlocode: null,
							timezone: 'America/Los_Angeles',
							ref: null,
						},
						ref: 'id-556359',
						vat_numbers: [],
					},
				],
				buyers: [],
				sellers: [],
				importers_of_record: [],
				items: [],
				legs: {
					_object: '/api/refs/collection',
					ref_type: '/shipment_leg',
					link: 'https://api.flexport.com/shipment_legs?f.shipment.id=502170',
				},
				customs_entries: {
					_object: '/api/refs/collection',
					ref_type: '/customs_entry',
					link: 'https://api.flexport.com/customs_entries?f.shipment.id=502170',
				},
				commercial_invoices: {
					_object: '/api/refs/collection',
					ref_type: '/commercial_invoice',
					link:
						'https://api.flexport.com/commercial_invoices?f.shipment.id=502170',
				},
				documents: {
					_object: '/api/refs/collection',
					ref_type: '/document',
					link: 'https://api.flexport.com/documents?f.shipment.id=502170',
				},
				departure_date: '2019-03-18T12:00:00.000+08:00',
				arrival_date: '2019-03-29T12:00:00.000-05:00',
				picked_up_in_full_date: '2019-03-14T12:00:00.000+08:00',
				delivered_in_full_date: null,
			},
			{
				metadata: {},
				_object: '/shipment',
				id: 502173,
				name: 'API LCL DEMO AWB#888',
				booking: {
					_object: '/api/refs/object',
					ref_type: '/booking',
					link: 'https://api.flexport.com/bookings/81912',
					id: 81912,
				},
				transportation_mode: 'ocean',
				freight_type: 'door_to_door',
				incoterm: 'DAP',
				calculated_weight: {
					value: 1000,
					unit: 'kg',
					_object: '/quantity/weight',
				},
				calculated_volume: {
					value: 10,
					unit: 'cbm',
					_object: '/quantity/volume',
				},
				pieces: 100,
				it_number: null,
				created_date: '2019-03-09T14:39:15.380Z',
				status: 'seller_location',
				priority: 'standard',
				updated_at: '2020-03-04T12:29:26.428Z',
				archived_at: null,
				estimated_departure_date: '2020-01-16T12:00:00.000+08:00',
				actual_departure_date: null,
				estimated_arrival_date: '2020-02-04T12:00:00.000-06:00',
				actual_arrival_date: null,
				estimated_picked_up_in_full_date: null,
				actual_picked_up_in_full_date: null,
				estimated_delivered_in_full_date: null,
				actual_delivered_in_full_date: null,
				cargo_ready_date: '2019-02-24',
				air_shipment: null,
				ocean_shipment: {
					_object: '/ocean/shipment',
					is_lcl: false,
					house_bill_number: '',
					master_bill_number: null,
					carrier_booking_number: null,
					containers: {
						_object: '/api/refs/collection',
						ref_type: '/ocean/shipment_container',
						link:
							'https://api.flexport.com/ocean/shipment_containers?f.shipment.id=502173',
					},
				},
				shippers: [
					{
						_object: '/company_entity',
						id: 566428,
						name: 'Flexport Demo Shipper',
						mailing_address: {
							_object: '/address',
							street_address: '1 Queen St',
							street_address2: null,
							city: 'Causeway Bay',
							state: 'Hong Kong',
							country: 'Hong Kong',
							country_code: 'HK',
							zip: null,
							unlocode: null,
							timezone: 'Asia/Hong_Kong',
							ref: null,
						},
						ref: 'id-566428',
						vat_numbers: [],
					},
				],
				consignees: [
					{
						_object: '/company_entity',
						id: 556359,
						name: 'Bookings Test Consignee',
						mailing_address: {
							_object: '/address',
							street_address: '760 MARKET ST FL 8',
							street_address2: '',
							city: 'San Francisco',
							state: 'CA',
							country: 'United States',
							country_code: 'US',
							zip: '94102-2300',
							unlocode: null,
							timezone: 'America/Los_Angeles',
							ref: null,
						},
						ref: 'id-556359',
						vat_numbers: [],
					},
				],
				buyers: [],
				sellers: [],
				importers_of_record: [],
				items: [],
				legs: {
					_object: '/api/refs/collection',
					ref_type: '/shipment_leg',
					link: 'https://api.flexport.com/shipment_legs?f.shipment.id=502173',
				},
				customs_entries: {
					_object: '/api/refs/collection',
					ref_type: '/customs_entry',
					link: 'https://api.flexport.com/customs_entries?f.shipment.id=502173',
				},
				commercial_invoices: {
					_object: '/api/refs/collection',
					ref_type: '/commercial_invoice',
					link:
						'https://api.flexport.com/commercial_invoices?f.shipment.id=502173',
				},
				documents: {
					_object: '/api/refs/collection',
					ref_type: '/document',
					link: 'https://api.flexport.com/documents?f.shipment.id=502173',
				},
				departure_date: '2020-01-16T12:00:00.000+08:00',
				arrival_date: '2020-02-04T12:00:00.000-06:00',
				picked_up_in_full_date: null,
				delivered_in_full_date: null,
			},
			{
				metadata: {},
				_object: '/shipment',
				id: 502232,
				name: 'API TEST 3 AWB#12345',
				booking: {
					_object: '/api/refs/object',
					ref_type: '/booking',
					link: 'https://api.flexport.com/bookings/81926',
					id: 81926,
				},
				transportation_mode: 'ocean',
				freight_type: 'door_to_door',
				incoterm: 'DAP',
				calculated_weight: {
					value: 1000,
					unit: 'kg',
					_object: '/quantity/weight',
				},
				calculated_volume: {
					value: 30,
					unit: 'cbm',
					_object: '/quantity/volume',
				},
				pieces: 50,
				it_number: null,
				created_date: '2019-03-11T01:21:45.212Z',
				status: 'seller_location',
				priority: 'standard',
				updated_at: '2020-03-25T06:57:22.303Z',
				archived_at: null,
				estimated_departure_date: '2019-03-19T12:00:00.000+08:00',
				actual_departure_date: null,
				estimated_arrival_date: '2019-03-28T12:00:00.000-07:00',
				actual_arrival_date: null,
				estimated_picked_up_in_full_date: '2019-03-15T12:00:00.000+08:00',
				actual_picked_up_in_full_date: null,
				estimated_delivered_in_full_date: '2019-03-30T19:00:00.000Z',
				actual_delivered_in_full_date: null,
				cargo_ready_date: '2019-03-27',
				air_shipment: null,
				ocean_shipment: {
					_object: '/ocean/shipment',
					is_lcl: false,
					house_bill_number: '',
					master_bill_number: null,
					carrier_booking_number: '3E3E3EE33',
					containers: {
						_object: '/api/refs/collection',
						ref_type: '/ocean/shipment_container',
						link:
							'https://api.flexport.com/ocean/shipment_containers?f.shipment.id=502232',
					},
				},
				shippers: [
					{
						_object: '/company_entity',
						id: 566428,
						name: 'Flexport Demo Shipper',
						mailing_address: {
							_object: '/address',
							street_address: '1 Queen St',
							street_address2: null,
							city: 'Causeway Bay',
							state: 'Hong Kong',
							country: 'Hong Kong',
							country_code: 'HK',
							zip: null,
							unlocode: null,
							timezone: 'Asia/Hong_Kong',
							ref: null,
						},
						ref: 'id-566428',
						vat_numbers: [],
					},
				],
				consignees: [
					{
						_object: '/company_entity',
						id: 556359,
						name: 'Bookings Test Consignee',
						mailing_address: {
							_object: '/address',
							street_address: '760 MARKET ST FL 8',
							street_address2: '',
							city: 'San Francisco',
							state: 'CA',
							country: 'United States',
							country_code: 'US',
							zip: '94102-2300',
							unlocode: null,
							timezone: 'America/Los_Angeles',
							ref: null,
						},
						ref: 'id-556359',
						vat_numbers: [],
					},
				],
				buyers: [],
				sellers: [],
				importers_of_record: [],
				items: [],
				legs: {
					_object: '/api/refs/collection',
					ref_type: '/shipment_leg',
					link: 'https://api.flexport.com/shipment_legs?f.shipment.id=502232',
				},
				customs_entries: {
					_object: '/api/refs/collection',
					ref_type: '/customs_entry',
					link: 'https://api.flexport.com/customs_entries?f.shipment.id=502232',
				},
				commercial_invoices: {
					_object: '/api/refs/collection',
					ref_type: '/commercial_invoice',
					link:
						'https://api.flexport.com/commercial_invoices?f.shipment.id=502232',
				},
				documents: {
					_object: '/api/refs/collection',
					ref_type: '/document',
					link: 'https://api.flexport.com/documents?f.shipment.id=502232',
				},
				departure_date: '2019-03-19T12:00:00.000+08:00',
				arrival_date: '2019-03-28T12:00:00.000-07:00',
				picked_up_in_full_date: '2019-03-15T12:00:00.000+08:00',
				delivered_in_full_date: null,
			},
			{
				metadata: {},
				_object: '/shipment',
				id: 504720,
				name: 'HBL task manual booking',
				booking: {
					_object: '/api/refs/object',
					ref_type: '/booking',
					link: 'https://api.flexport.com/bookings/83022',
					id: 83022,
				},
				transportation_mode: 'ocean',
				freight_type: 'door_to_door',
				incoterm: 'EXW',
				calculated_weight: {
					value: 1100,
					unit: 'kg',
					_object: '/quantity/weight',
				},
				calculated_volume: {
					value: 49,
					unit: 'cbm',
					_object: '/quantity/volume',
				},
				pieces: 170,
				it_number: null,
				created_date: '2019-03-14T10:28:21.434Z',
				status: 'seller_location',
				priority: 'standard',
				updated_at: '2020-03-04T12:29:28.269Z',
				archived_at: null,
				estimated_departure_date: '2019-03-20T12:00:00.000+08:00',
				actual_departure_date: null,
				estimated_arrival_date: '2019-04-21T12:00:00.000-04:00',
				actual_arrival_date: null,
				estimated_picked_up_in_full_date: '2019-03-19T12:00:00.000+08:00',
				actual_picked_up_in_full_date: null,
				estimated_delivered_in_full_date: null,
				actual_delivered_in_full_date: null,
				cargo_ready_date: '2019-03-13',
				air_shipment: null,
				ocean_shipment: {
					_object: '/ocean/shipment',
					is_lcl: false,
					house_bill_number: 'FLXTFHKUS504720A',
					master_bill_number: null,
					carrier_booking_number: 'dfssdfdsdfsfwe',
					containers: {
						_object: '/api/refs/collection',
						ref_type: '/ocean/shipment_container',
						link:
							'https://api.flexport.com/ocean/shipment_containers?f.shipment.id=504720',
					},
				},
				shippers: [
					{
						_object: '/company_entity',
						id: 566428,
						name: 'Flexport Demo Shipper',
						mailing_address: {
							_object: '/address',
							street_address: '1 Queen St',
							street_address2: null,
							city: 'Causeway Bay',
							state: 'Hong Kong',
							country: 'Hong Kong',
							country_code: 'HK',
							zip: null,
							unlocode: null,
							timezone: 'Asia/Hong_Kong',
							ref: null,
						},
						ref: 'id-566428',
						vat_numbers: [],
					},
				],
				consignees: [
					{
						_object: '/company_entity',
						id: 556359,
						name: 'Bookings Test Consignee',
						mailing_address: {
							_object: '/address',
							street_address: '760 MARKET ST FL 8',
							street_address2: '',
							city: 'San Francisco',
							state: 'CA',
							country: 'United States',
							country_code: 'US',
							zip: '94102-2300',
							unlocode: null,
							timezone: 'America/Los_Angeles',
							ref: null,
						},
						ref: 'id-556359',
						vat_numbers: [],
					},
				],
				buyers: [],
				sellers: [],
				importers_of_record: [],
				items: [],
				legs: {
					_object: '/api/refs/collection',
					ref_type: '/shipment_leg',
					link: 'https://api.flexport.com/shipment_legs?f.shipment.id=504720',
				},
				customs_entries: {
					_object: '/api/refs/collection',
					ref_type: '/customs_entry',
					link: 'https://api.flexport.com/customs_entries?f.shipment.id=504720',
				},
				commercial_invoices: {
					_object: '/api/refs/collection',
					ref_type: '/commercial_invoice',
					link:
						'https://api.flexport.com/commercial_invoices?f.shipment.id=504720',
				},
				documents: {
					_object: '/api/refs/collection',
					ref_type: '/document',
					link: 'https://api.flexport.com/documents?f.shipment.id=504720',
				},
				departure_date: '2019-03-20T12:00:00.000+08:00',
				arrival_date: '2019-04-21T12:00:00.000-04:00',
				picked_up_in_full_date: '2019-03-19T12:00:00.000+08:00',
				delivered_in_full_date: null,
			},
			{
				metadata: {},
				_object: '/shipment',
				id: 508266,
				name: 'PO 1880, CRD 3/21, 1x20GP',
				booking: {
					_object: '/api/refs/object',
					ref_type: '/booking',
					link: 'https://api.flexport.com/bookings/84262',
					id: 84262,
				},
				transportation_mode: 'ocean',
				freight_type: 'port_to_door',
				incoterm: 'FOB',
				calculated_weight: {
					value: 1100,
					unit: 'kg',
					_object: '/quantity/weight',
				},
				calculated_volume: {
					value: 30,
					unit: 'cbm',
					_object: '/quantity/volume',
				},
				pieces: 100,
				it_number: null,
				created_date: '2019-03-21T03:16:12.546Z',
				status: 'seller_location',
				priority: 'standard',
				updated_at: '2020-03-04T12:29:28.729Z',
				archived_at: null,
				estimated_departure_date: '2019-03-31T12:00:00.000+08:00',
				actual_departure_date: null,
				estimated_arrival_date: '2019-04-16T12:00:00.000-07:00',
				actual_arrival_date: null,
				estimated_picked_up_in_full_date: '2019-03-27T12:00:00.000+08:00',
				actual_picked_up_in_full_date: null,
				estimated_delivered_in_full_date: null,
				actual_delivered_in_full_date: null,
				cargo_ready_date: '2019-03-21',
				air_shipment: null,
				ocean_shipment: {
					_object: '/ocean/shipment',
					is_lcl: false,
					house_bill_number: 'FLXTFCNUS508266A',
					master_bill_number: null,
					carrier_booking_number: '1234576',
					containers: {
						_object: '/api/refs/collection',
						ref_type: '/ocean/shipment_container',
						link:
							'https://api.flexport.com/ocean/shipment_containers?f.shipment.id=508266',
					},
				},
				shippers: [
					{
						_object: '/company_entity',
						id: 566428,
						name: 'Flexport Demo Shipper',
						mailing_address: {
							_object: '/address',
							street_address: '1 Queen St',
							street_address2: null,
							city: 'Causeway Bay',
							state: 'Hong Kong',
							country: 'Hong Kong',
							country_code: 'HK',
							zip: null,
							unlocode: null,
							timezone: 'Asia/Hong_Kong',
							ref: null,
						},
						ref: 'id-566428',
						vat_numbers: [],
					},
				],
				consignees: [
					{
						_object: '/company_entity',
						id: 556359,
						name: 'Bookings Test Consignee',
						mailing_address: {
							_object: '/address',
							street_address: '760 MARKET ST FL 8',
							street_address2: '',
							city: 'San Francisco',
							state: 'CA',
							country: 'United States',
							country_code: 'US',
							zip: '94102-2300',
							unlocode: null,
							timezone: 'America/Los_Angeles',
							ref: null,
						},
						ref: 'id-556359',
						vat_numbers: [],
					},
				],
				buyers: [],
				sellers: [],
				importers_of_record: [],
				items: [],
				legs: {
					_object: '/api/refs/collection',
					ref_type: '/shipment_leg',
					link: 'https://api.flexport.com/shipment_legs?f.shipment.id=508266',
				},
				customs_entries: {
					_object: '/api/refs/collection',
					ref_type: '/customs_entry',
					link: 'https://api.flexport.com/customs_entries?f.shipment.id=508266',
				},
				commercial_invoices: {
					_object: '/api/refs/collection',
					ref_type: '/commercial_invoice',
					link:
						'https://api.flexport.com/commercial_invoices?f.shipment.id=508266',
				},
				documents: {
					_object: '/api/refs/collection',
					ref_type: '/document',
					link: 'https://api.flexport.com/documents?f.shipment.id=508266',
				},
				departure_date: '2019-03-31T12:00:00.000+08:00',
				arrival_date: '2019-04-16T12:00:00.000-07:00',
				picked_up_in_full_date: '2019-03-27T12:00:00.000+08:00',
				delivered_in_full_date: null,
			},
			{
				metadata: {},
				_object: '/shipment',
				id: 508272,
				name: 'TEST 2 CRD 3/21 ',
				booking: {
					_object: '/api/refs/object',
					ref_type: '/booking',
					link: 'https://api.flexport.com/bookings/84266',
					id: 84266,
				},
				transportation_mode: 'ocean',
				freight_type: 'port_to_door',
				incoterm: 'FOB',
				calculated_weight: {
					value: 1111,
					unit: 'kg',
					_object: '/quantity/weight',
				},
				calculated_volume: {
					value: 44,
					unit: 'cbm',
					_object: '/quantity/volume',
				},
				pieces: 11,
				it_number: null,
				created_date: '2019-03-21T03:21:32.842Z',
				status: 'seller_location',
				priority: 'standard',
				updated_at: '2020-03-04T12:29:28.545Z',
				archived_at: null,
				estimated_departure_date: '2019-03-31T12:00:00.000+08:00',
				actual_departure_date: null,
				estimated_arrival_date: '2019-04-16T12:00:00.000-07:00',
				actual_arrival_date: null,
				estimated_picked_up_in_full_date: '2019-03-27T12:00:00.000+08:00',
				actual_picked_up_in_full_date: null,
				estimated_delivered_in_full_date: null,
				actual_delivered_in_full_date: null,
				cargo_ready_date: '2019-03-21',
				air_shipment: null,
				ocean_shipment: {
					_object: '/ocean/shipment',
					is_lcl: false,
					house_bill_number: '',
					master_bill_number: null,
					carrier_booking_number: '123443',
					containers: {
						_object: '/api/refs/collection',
						ref_type: '/ocean/shipment_container',
						link:
							'https://api.flexport.com/ocean/shipment_containers?f.shipment.id=508272',
					},
				},
				shippers: [
					{
						_object: '/company_entity',
						id: 566428,
						name: 'Flexport Demo Shipper',
						mailing_address: {
							_object: '/address',
							street_address: '1 Queen St',
							street_address2: null,
							city: 'Causeway Bay',
							state: 'Hong Kong',
							country: 'Hong Kong',
							country_code: 'HK',
							zip: null,
							unlocode: null,
							timezone: 'Asia/Hong_Kong',
							ref: null,
						},
						ref: 'id-566428',
						vat_numbers: [],
					},
				],
				consignees: [
					{
						_object: '/company_entity',
						id: 556359,
						name: 'Bookings Test Consignee',
						mailing_address: {
							_object: '/address',
							street_address: '760 MARKET ST FL 8',
							street_address2: '',
							city: 'San Francisco',
							state: 'CA',
							country: 'United States',
							country_code: 'US',
							zip: '94102-2300',
							unlocode: null,
							timezone: 'America/Los_Angeles',
							ref: null,
						},
						ref: 'id-556359',
						vat_numbers: [],
					},
				],
				buyers: [],
				sellers: [],
				importers_of_record: [],
				items: [],
				legs: {
					_object: '/api/refs/collection',
					ref_type: '/shipment_leg',
					link: 'https://api.flexport.com/shipment_legs?f.shipment.id=508272',
				},
				customs_entries: {
					_object: '/api/refs/collection',
					ref_type: '/customs_entry',
					link: 'https://api.flexport.com/customs_entries?f.shipment.id=508272',
				},
				commercial_invoices: {
					_object: '/api/refs/collection',
					ref_type: '/commercial_invoice',
					link:
						'https://api.flexport.com/commercial_invoices?f.shipment.id=508272',
				},
				documents: {
					_object: '/api/refs/collection',
					ref_type: '/document',
					link: 'https://api.flexport.com/documents?f.shipment.id=508272',
				},
				departure_date: '2019-03-31T12:00:00.000+08:00',
				arrival_date: '2019-04-16T12:00:00.000-07:00',
				picked_up_in_full_date: '2019-03-27T12:00:00.000+08:00',
				delivered_in_full_date: null,
			},
			{
				metadata: {},
				_object: '/shipment',
				id: 508275,
				name: 'TEST 3 CRD 3/21',
				booking: {
					_object: '/api/refs/object',
					ref_type: '/booking',
					link: 'https://api.flexport.com/bookings/84267',
					id: 84267,
				},
				transportation_mode: 'ocean',
				freight_type: 'port_to_door',
				incoterm: 'FOB',
				calculated_weight: {
					value: 1111,
					unit: 'kg',
					_object: '/quantity/weight',
				},
				calculated_volume: {
					value: 44,
					unit: 'cbm',
					_object: '/quantity/volume',
				},
				pieces: 11,
				it_number: null,
				created_date: '2019-03-21T03:25:42.686Z',
				status: 'in_transit_to_final_destination',
				priority: 'standard',
				updated_at: '2020-03-04T12:29:28.443Z',
				archived_at: null,
				estimated_departure_date: '2019-03-31T12:00:00.000+08:00',
				actual_departure_date: '2019-03-28T12:00:00.000+08:00',
				estimated_arrival_date: '2019-04-16T16:00:00.000-07:00',
				actual_arrival_date: '2019-04-16T12:00:00.000-07:00',
				estimated_picked_up_in_full_date: '2019-03-27T12:00:00.000+08:00',
				actual_picked_up_in_full_date: '2019-03-27T12:00:00.000+08:00',
				estimated_delivered_in_full_date: '2019-04-19T12:00:00.000-07:00',
				actual_delivered_in_full_date: null,
				cargo_ready_date: '2019-03-21',
				air_shipment: null,
				ocean_shipment: {
					_object: '/ocean/shipment',
					is_lcl: false,
					house_bill_number: '',
					master_bill_number: null,
					carrier_booking_number: '123333D',
					containers: {
						_object: '/api/refs/collection',
						ref_type: '/ocean/shipment_container',
						link:
							'https://api.flexport.com/ocean/shipment_containers?f.shipment.id=508275',
					},
				},
				shippers: [
					{
						_object: '/company_entity',
						id: 566428,
						name: 'Flexport Demo Shipper',
						mailing_address: {
							_object: '/address',
							street_address: '1 Queen St',
							street_address2: null,
							city: 'Causeway Bay',
							state: 'Hong Kong',
							country: 'Hong Kong',
							country_code: 'HK',
							zip: null,
							unlocode: null,
							timezone: 'Asia/Hong_Kong',
							ref: null,
						},
						ref: 'id-566428',
						vat_numbers: [],
					},
				],
				consignees: [
					{
						_object: '/company_entity',
						id: 556359,
						name: 'Bookings Test Consignee',
						mailing_address: {
							_object: '/address',
							street_address: '760 MARKET ST FL 8',
							street_address2: '',
							city: 'San Francisco',
							state: 'CA',
							country: 'United States',
							country_code: 'US',
							zip: '94102-2300',
							unlocode: null,
							timezone: 'America/Los_Angeles',
							ref: null,
						},
						ref: 'id-556359',
						vat_numbers: [],
					},
				],
				buyers: [],
				sellers: [],
				importers_of_record: [],
				items: [],
				legs: {
					_object: '/api/refs/collection',
					ref_type: '/shipment_leg',
					link: 'https://api.flexport.com/shipment_legs?f.shipment.id=508275',
				},
				customs_entries: {
					_object: '/api/refs/collection',
					ref_type: '/customs_entry',
					link: 'https://api.flexport.com/customs_entries?f.shipment.id=508275',
				},
				commercial_invoices: {
					_object: '/api/refs/collection',
					ref_type: '/commercial_invoice',
					link:
						'https://api.flexport.com/commercial_invoices?f.shipment.id=508275',
				},
				documents: {
					_object: '/api/refs/collection',
					ref_type: '/document',
					link: 'https://api.flexport.com/documents?f.shipment.id=508275',
				},
				departure_date: '2019-03-28T12:00:00.000+08:00',
				arrival_date: '2019-04-16T12:00:00.000-07:00',
				picked_up_in_full_date: '2019-03-27T12:00:00.000+08:00',
				delivered_in_full_date: null,
			},
			{
				metadata: {},
				_object: '/shipment',
				id: 508281,
				name: 'TEST 4 CRD 3/21',
				booking: {
					_object: '/api/refs/object',
					ref_type: '/booking',
					link: 'https://api.flexport.com/bookings/84271',
					id: 84271,
				},
				transportation_mode: 'ocean',
				freight_type: 'port_to_door',
				incoterm: 'FOB',
				calculated_weight: {
					value: 1111,
					unit: 'kg',
					_object: '/quantity/weight',
				},
				calculated_volume: {
					value: 44,
					unit: 'cbm',
					_object: '/quantity/volume',
				},
				pieces: 11,
				it_number: null,
				created_date: '2019-03-21T03:35:33.887Z',
				status: 'seller_location',
				priority: 'standard',
				updated_at: '2020-03-04T12:29:28.344Z',
				archived_at: null,
				estimated_departure_date: '2019-03-31T12:00:00.000+08:00',
				actual_departure_date: null,
				estimated_arrival_date: '2019-04-16T12:00:00.000-07:00',
				actual_arrival_date: null,
				estimated_picked_up_in_full_date: '2019-03-27T12:00:00.000+08:00',
				actual_picked_up_in_full_date: null,
				estimated_delivered_in_full_date: null,
				actual_delivered_in_full_date: null,
				cargo_ready_date: '2019-03-21',
				air_shipment: null,
				ocean_shipment: {
					_object: '/ocean/shipment',
					is_lcl: false,
					house_bill_number: '',
					master_bill_number: null,
					carrier_booking_number: 'DFSVDDDV',
					containers: {
						_object: '/api/refs/collection',
						ref_type: '/ocean/shipment_container',
						link:
							'https://api.flexport.com/ocean/shipment_containers?f.shipment.id=508281',
					},
				},
				shippers: [
					{
						_object: '/company_entity',
						id: 566428,
						name: 'Flexport Demo Shipper',
						mailing_address: {
							_object: '/address',
							street_address: '1 Queen St',
							street_address2: null,
							city: 'Causeway Bay',
							state: 'Hong Kong',
							country: 'Hong Kong',
							country_code: 'HK',
							zip: null,
							unlocode: null,
							timezone: 'Asia/Hong_Kong',
							ref: null,
						},
						ref: 'id-566428',
						vat_numbers: [],
					},
				],
				consignees: [
					{
						_object: '/company_entity',
						id: 556359,
						name: 'Bookings Test Consignee',
						mailing_address: {
							_object: '/address',
							street_address: '760 MARKET ST FL 8',
							street_address2: '',
							city: 'San Francisco',
							state: 'CA',
							country: 'United States',
							country_code: 'US',
							zip: '94102-2300',
							unlocode: null,
							timezone: 'America/Los_Angeles',
							ref: null,
						},
						ref: 'id-556359',
						vat_numbers: [],
					},
				],
				buyers: [],
				sellers: [],
				importers_of_record: [],
				items: [],
				legs: {
					_object: '/api/refs/collection',
					ref_type: '/shipment_leg',
					link: 'https://api.flexport.com/shipment_legs?f.shipment.id=508281',
				},
				customs_entries: {
					_object: '/api/refs/collection',
					ref_type: '/customs_entry',
					link: 'https://api.flexport.com/customs_entries?f.shipment.id=508281',
				},
				commercial_invoices: {
					_object: '/api/refs/collection',
					ref_type: '/commercial_invoice',
					link:
						'https://api.flexport.com/commercial_invoices?f.shipment.id=508281',
				},
				documents: {
					_object: '/api/refs/collection',
					ref_type: '/document',
					link: 'https://api.flexport.com/documents?f.shipment.id=508281',
				},
				departure_date: '2019-03-31T12:00:00.000+08:00',
				arrival_date: '2019-04-16T12:00:00.000-07:00',
				picked_up_in_full_date: '2019-03-27T12:00:00.000+08:00',
				delivered_in_full_date: null,
			},
			{
				metadata: {},
				_object: '/shipment',
				id: 508282,
				name: 'TEST 5 CRD 3/21',
				booking: {
					_object: '/api/refs/object',
					ref_type: '/booking',
					link: 'https://api.flexport.com/bookings/84272',
					id: 84272,
				},
				transportation_mode: 'ocean',
				freight_type: 'port_to_door',
				incoterm: 'FOB',
				calculated_weight: {
					value: 1111,
					unit: 'kg',
					_object: '/quantity/weight',
				},
				calculated_volume: {
					value: 44,
					unit: 'cbm',
					_object: '/quantity/volume',
				},
				pieces: 11,
				it_number: null,
				created_date: '2019-03-21T03:35:46.894Z',
				status: 'seller_location',
				priority: 'standard',
				updated_at: '2020-03-04T12:29:28.308Z',
				archived_at: null,
				estimated_departure_date: '2019-03-31T12:00:00.000+08:00',
				actual_departure_date: null,
				estimated_arrival_date: '2019-04-16T12:00:00.000-07:00',
				actual_arrival_date: null,
				estimated_picked_up_in_full_date: '2019-03-27T12:00:00.000+08:00',
				actual_picked_up_in_full_date: null,
				estimated_delivered_in_full_date: null,
				actual_delivered_in_full_date: null,
				cargo_ready_date: '2019-03-21',
				air_shipment: null,
				ocean_shipment: {
					_object: '/ocean/shipment',
					is_lcl: false,
					house_bill_number: '',
					master_bill_number: null,
					carrier_booking_number: 'DFBDFBDFBDF',
					containers: {
						_object: '/api/refs/collection',
						ref_type: '/ocean/shipment_container',
						link:
							'https://api.flexport.com/ocean/shipment_containers?f.shipment.id=508282',
					},
				},
				shippers: [
					{
						_object: '/company_entity',
						id: 566428,
						name: 'Flexport Demo Shipper',
						mailing_address: {
							_object: '/address',
							street_address: '1 Queen St',
							street_address2: null,
							city: 'Causeway Bay',
							state: 'Hong Kong',
							country: 'Hong Kong',
							country_code: 'HK',
							zip: null,
							unlocode: null,
							timezone: 'Asia/Hong_Kong',
							ref: null,
						},
						ref: 'id-566428',
						vat_numbers: [],
					},
				],
				consignees: [
					{
						_object: '/company_entity',
						id: 556359,
						name: 'Bookings Test Consignee',
						mailing_address: {
							_object: '/address',
							street_address: '760 MARKET ST FL 8',
							street_address2: '',
							city: 'San Francisco',
							state: 'CA',
							country: 'United States',
							country_code: 'US',
							zip: '94102-2300',
							unlocode: null,
							timezone: 'America/Los_Angeles',
							ref: null,
						},
						ref: 'id-556359',
						vat_numbers: [],
					},
				],
				buyers: [],
				sellers: [],
				importers_of_record: [],
				items: [],
				legs: {
					_object: '/api/refs/collection',
					ref_type: '/shipment_leg',
					link: 'https://api.flexport.com/shipment_legs?f.shipment.id=508282',
				},
				customs_entries: {
					_object: '/api/refs/collection',
					ref_type: '/customs_entry',
					link: 'https://api.flexport.com/customs_entries?f.shipment.id=508282',
				},
				commercial_invoices: {
					_object: '/api/refs/collection',
					ref_type: '/commercial_invoice',
					link:
						'https://api.flexport.com/commercial_invoices?f.shipment.id=508282',
				},
				documents: {
					_object: '/api/refs/collection',
					ref_type: '/document',
					link: 'https://api.flexport.com/documents?f.shipment.id=508282',
				},
				departure_date: '2019-03-31T12:00:00.000+08:00',
				arrival_date: '2019-04-16T12:00:00.000-07:00',
				picked_up_in_full_date: '2019-03-27T12:00:00.000+08:00',
				delivered_in_full_date: null,
			},
			{
				metadata: {},
				_object: '/shipment',
				id: 508284,
				name: 'TEST PO 1990, CRD 3/21',
				booking: {
					_object: '/api/refs/object',
					ref_type: '/booking',
					link: 'https://api.flexport.com/bookings/84273',
					id: 84273,
				},
				transportation_mode: 'ocean',
				freight_type: 'port_to_door',
				incoterm: 'FOB',
				calculated_weight: {
					value: 1100,
					unit: 'kg',
					_object: '/quantity/weight',
				},
				calculated_volume: {
					value: 30,
					unit: 'cbm',
					_object: '/quantity/volume',
				},
				pieces: 100,
				it_number: null,
				created_date: '2019-03-21T03:35:57.920Z',
				status: 'seller_location',
				priority: 'standard',
				updated_at: '2020-03-04T12:29:28.584Z',
				archived_at: null,
				estimated_departure_date: '2019-03-31T12:00:00.000+08:00',
				actual_departure_date: null,
				estimated_arrival_date: '2019-04-16T12:00:00.000-07:00',
				actual_arrival_date: null,
				estimated_picked_up_in_full_date: '2019-03-27T12:00:00.000+08:00',
				actual_picked_up_in_full_date: null,
				estimated_delivered_in_full_date: null,
				actual_delivered_in_full_date: null,
				cargo_ready_date: '2019-03-21',
				air_shipment: null,
				ocean_shipment: {
					_object: '/ocean/shipment',
					is_lcl: false,
					house_bill_number: 'FLXTFCNUS508284A',
					master_bill_number: null,
					carrier_booking_number: 'DFVDFDVDDV',
					containers: {
						_object: '/api/refs/collection',
						ref_type: '/ocean/shipment_container',
						link:
							'https://api.flexport.com/ocean/shipment_containers?f.shipment.id=508284',
					},
				},
				shippers: [
					{
						_object: '/company_entity',
						id: 566428,
						name: 'Flexport Demo Shipper',
						mailing_address: {
							_object: '/address',
							street_address: '1 Queen St',
							street_address2: null,
							city: 'Causeway Bay',
							state: 'Hong Kong',
							country: 'Hong Kong',
							country_code: 'HK',
							zip: null,
							unlocode: null,
							timezone: 'Asia/Hong_Kong',
							ref: null,
						},
						ref: 'id-566428',
						vat_numbers: [],
					},
				],
				consignees: [
					{
						_object: '/company_entity',
						id: 556359,
						name: 'Bookings Test Consignee',
						mailing_address: {
							_object: '/address',
							street_address: '760 MARKET ST FL 8',
							street_address2: '',
							city: 'San Francisco',
							state: 'CA',
							country: 'United States',
							country_code: 'US',
							zip: '94102-2300',
							unlocode: null,
							timezone: 'America/Los_Angeles',
							ref: null,
						},
						ref: 'id-556359',
						vat_numbers: [],
					},
				],
				buyers: [],
				sellers: [],
				importers_of_record: [],
				items: [],
				legs: {
					_object: '/api/refs/collection',
					ref_type: '/shipment_leg',
					link: 'https://api.flexport.com/shipment_legs?f.shipment.id=508284',
				},
				customs_entries: {
					_object: '/api/refs/collection',
					ref_type: '/customs_entry',
					link: 'https://api.flexport.com/customs_entries?f.shipment.id=508284',
				},
				commercial_invoices: {
					_object: '/api/refs/collection',
					ref_type: '/commercial_invoice',
					link:
						'https://api.flexport.com/commercial_invoices?f.shipment.id=508284',
				},
				documents: {
					_object: '/api/refs/collection',
					ref_type: '/document',
					link: 'https://api.flexport.com/documents?f.shipment.id=508284',
				},
				departure_date: '2019-03-31T12:00:00.000+08:00',
				arrival_date: '2019-04-16T12:00:00.000-07:00',
				picked_up_in_full_date: '2019-03-27T12:00:00.000+08:00',
				delivered_in_full_date: null,
			},
		],
	},
	error: null,
}
