module.exports = {
	_object: '/api/response',
	self: 'https://api.flexport.com/shipment_legs?f.shipment.id=637102',
	version: 2,
	data: {
		_object: '/api/collections/paginated',
		prev: null,
		next: null,
		total_count: 3,
		data: [
			{
				_object: '/shipment_leg',
				id: 5622067,
				shipment: {
					_object: '/api/refs/object',
					ref_type: '/shipment',
					link: 'https://api.flexport.com/shipments/637102',
					id: 637102,
				},
				estimated_arrival_date: null,
				actual_arrival_date: null,
				estimated_departure_date: null,
				actual_departure_date: null,
				cargo_ready_date: null,
				additional_dates: {},
				origin: {
					_object: '/shipment_node',
					tags: [],
					place: {
						_object: '/place',
						name: 'Los Angeles, CA',
						address: {
							_object: '/address',
							street_address: null,
							street_address2: null,
							city: 'Los Angeles',
							state: 'CA',
							country: 'United States',
							country_code: 'US',
							zip: null,
							unlocode: 'USLAX',
							timezone: 'America/Los_Angeles',
							ref: 'id-41538',
						},
						details: [
							{
								_object: '/ocean/railport',
								port_code: '2704',
							},
							{
								_object: '/trucking/port',
								port_code: '2704',
							},
							{
								_object: '/ocean/port',
								port_code: '2704',
							},
						],
					},
					terminal: null,
				},
				destination: {
					_object: '/shipment_node',
					tags: ['port_of_unloading'],
					place: {
						_object: '/place',
						name: 'New York, NY / Newark, NJ',
						address: {
							_object: '/address',
							street_address: null,
							street_address2: null,
							city: 'Newark',
							state: 'NJ',
							country: 'United States',
							country_code: 'US',
							zip: null,
							unlocode: 'USNYC',
							timezone: 'America/New_York',
							ref: 'id-41601',
						},
						details: [
							{
								_object: '/ocean/railport',
								port_code: '4601',
							},
							{
								_object: '/trucking/port',
								port_code: '4601',
							},
							{
								_object: '/ocean/port',
								port_code: '4601',
							},
						],
					},
					terminal: null,
				},
				transportation_mode: 'rail',
				carrier_name: 'BarOle Trucking',
				ocean_leg: null,
				air_leg: null,
				trucking_leg: null,
				rail_leg: {
					_object: '/rail/shipment_leg',
					container_legs: {
						_object: '/api/refs/collection',
						ref_type: '/ocean/shipment_container_leg',
						link:
							'https://api.flexport.com/ocean/shipment_container_legs?f.leg.id=5622067',
					},
				},
			},
			{
				_object: '/shipment_leg',
				id: 5622068,
				shipment: {
					_object: '/api/refs/object',
					ref_type: '/shipment',
					link: 'https://api.flexport.com/shipments/637102',
					id: 637102,
				},
				estimated_arrival_date: null,
				actual_arrival_date: null,
				estimated_departure_date: null,
				actual_departure_date: null,
				cargo_ready_date: '2019-11-24',
				additional_dates: {
					cargo_ready_date: '2019-11-24',
				},
				origin: {
					_object: '/shipment_node',
					tags: ['origin_address'],
					place: {
						_object: '/place',
						name: 'RNO1',
						address: {
							_object: '/address',
							street_address: '1600 East Newlands Drive',
							street_address2: null,
							city: 'Fernley',
							state: 'NV',
							country: 'United States',
							country_code: 'US',
							zip: '89408',
							unlocode: null,
							timezone: 'America/Los_Angeles',
							ref: 'id-22006',
						},
						details: [],
					},
					terminal: null,
				},
				destination: {
					_object: '/shipment_node',
					tags: [],
					place: {
						_object: '/place',
						name: 'Los Angeles, CA',
						address: {
							_object: '/address',
							street_address: null,
							street_address2: null,
							city: 'Los Angeles',
							state: 'CA',
							country: 'United States',
							country_code: 'US',
							zip: null,
							unlocode: 'USLAX',
							timezone: 'America/Los_Angeles',
							ref: 'id-41538',
						},
						details: [
							{
								_object: '/ocean/railport',
								port_code: '2704',
							},
							{
								_object: '/trucking/port',
								port_code: '2704',
							},
							{
								_object: '/ocean/port',
								port_code: '2704',
							},
						],
					},
					terminal: null,
				},
				transportation_mode: 'truck',
				carrier_name: null,
				ocean_leg: null,
				air_leg: null,
				trucking_leg: {
					_object: '/trucking/shipment_leg',
					tracking_number: null,
					service_type: 'drayage',
					pieces: null,
					container_legs: {
						_object: '/api/refs/collection',
						ref_type: '/ocean/shipment_container_leg',
						link:
							'https://api.flexport.com/ocean/shipment_container_legs?f.leg.id=5622068',
					},
				},
				rail_leg: null,
			},
			{
				_object: '/shipment_leg',
				id: 5622069,
				shipment: {
					_object: '/api/refs/object',
					ref_type: '/shipment',
					link: 'https://api.flexport.com/shipments/637102',
					id: 637102,
				},
				estimated_arrival_date: null,
				actual_arrival_date: null,
				estimated_departure_date: null,
				actual_departure_date: null,
				cargo_ready_date: null,
				additional_dates: {},
				origin: {
					_object: '/shipment_node',
					tags: ['port_of_unloading'],
					place: {
						_object: '/place',
						name: 'New York, NY / Newark, NJ',
						address: {
							_object: '/address',
							street_address: null,
							street_address2: null,
							city: 'Newark',
							state: 'NJ',
							country: 'United States',
							country_code: 'US',
							zip: null,
							unlocode: 'USNYC',
							timezone: 'America/New_York',
							ref: 'id-41601',
						},
						details: [
							{
								_object: '/ocean/railport',
								port_code: '4601',
							},
							{
								_object: '/trucking/port',
								port_code: '4601',
							},
							{
								_object: '/ocean/port',
								port_code: '4601',
							},
						],
					},
					terminal: null,
				},
				destination: {
					_object: '/shipment_node',
					tags: ['destination_address'],
					place: {
						_object: '/place',
						name: 'CVG1',
						address: {
							_object: '/address',
							street_address: '1155 Worldwide Blvd.',
							street_address2: null,
							city: 'Hebron',
							state: 'KY',
							country: 'United States',
							country_code: 'US',
							zip: '41048',
							unlocode: null,
							timezone: 'America/New_York',
							ref: 'id-22003',
						},
						details: [],
					},
					terminal: null,
				},
				transportation_mode: 'truck',
				carrier_name: null,
				ocean_leg: null,
				air_leg: null,
				trucking_leg: {
					_object: '/trucking/shipment_leg',
					tracking_number: null,
					service_type: 'drayage',
					pieces: null,
					container_legs: {
						_object: '/api/refs/collection',
						ref_type: '/ocean/shipment_container_leg',
						link:
							'https://api.flexport.com/ocean/shipment_container_legs?f.leg.id=5622069',
					},
				},
				rail_leg: null,
			},
		],
	},
	error: null,
}
