module.exports = {
	_object: '/api/response',
	self: 'https://api.flexport.com/shipment_legs?f.shipment.id=719185',
	version: 2,
	data: {
		_object: '/api/collections/paginated',
		prev: null,
		next: null,
		total_count: 3,
		data: [
			{
				_object: '/shipment_leg',
				id: 6468173,
				shipment: {
					_object: '/api/refs/object',
					ref_type: '/shipment',
					link: 'https://api.flexport.com/shipments/719185',
					id: 719185,
				},
				estimated_arrival_date: '2020-03-05T12:00:00.000+08:00',
				actual_arrival_date: '2020-03-01T12:00:00.000+08:00',
				estimated_departure_date: '2020-03-05T12:00:00.000+08:00',
				actual_departure_date: '2020-03-01T12:00:00.000+08:00',
				cargo_ready_date: '2020-02-28',
				additional_dates: {
					cargo_ready_date: '2020-02-28',
					delivery_appointment_scheduled_for_date:
						'2020-03-05T12:00:00.000+08:00',
					delivery_completed: '2020-03-01T12:00:00.000+08:00',
				},
				origin: {
					_object: '/shipment_node',
					tags: ['origin_address'],
					place: {
						_object: '/place',
						name: 'Mirko Yantian Warehouse',
						address: {
							_object: '/address',
							street_address: '3435 Shenzhen Rd.',
							street_address2: '',
							city: 'Shenzhen',
							state: 'Guangdong',
							country: 'China',
							country_code: 'CN',
							zip: null,
							unlocode: null,
							timezone: 'Asia/Shanghai',
							ref: 'id-162815',
						},
						details: [],
					},
					terminal: null,
				},
				destination: {
					_object: '/shipment_node',
					tags: ['port_of_loading'],
					place: {
						_object: '/place',
						name: 'Shanghai, China',
						address: {
							_object: '/address',
							street_address: null,
							street_address2: null,
							city: 'Shanghai ',
							state: null,
							country: 'China',
							country_code: 'CN',
							zip: null,
							unlocode: 'CNSHG',
							timezone: 'Asia/Shanghai',
							ref: 'id-39042',
						},
						details: [
							{
								_object: '/trucking/port',
								port_code: '57035',
							},
							{
								_object: '/ocean/port',
								port_code: '57035',
							},
						],
					},
					terminal: null,
				},
				transportation_mode: 'truck',
				carrier_name: null,
				ocean_leg: null,
				air_leg: null,
				trucking_leg: {
					_object: '/trucking/shipment_leg',
					tracking_number: null,
					service_type: 'drayage',
					pieces: null,
					container_legs: {
						_object: '/api/refs/collection',
						ref_type: '/ocean/shipment_container_leg',
						link:
							'https://api.flexport.com/ocean/shipment_container_legs?f.leg.id=6468173',
					},
				},
				rail_leg: null,
			},
			{
				_object: '/shipment_leg',
				id: 6468174,
				shipment: {
					_object: '/api/refs/object',
					ref_type: '/shipment',
					link: 'https://api.flexport.com/shipments/719185',
					id: 719185,
				},
				estimated_arrival_date: null,
				actual_arrival_date: null,
				estimated_departure_date: null,
				actual_departure_date: null,
				cargo_ready_date: null,
				additional_dates: {},
				origin: {
					_object: '/shipment_node',
					tags: ['port_of_unloading', 'customs_entry', 'fmc_port_of_unloading'],
					place: {
						_object: '/place',
						name: 'Tacoma',
						address: {
							_object: '/address',
							street_address: null,
							street_address2: null,
							city: 'Tacoma',
							state: 'WA',
							country: 'United States',
							country_code: 'US',
							zip: null,
							unlocode: 'USTIW',
							timezone: 'America/Los_Angeles',
							ref: 'id-36164',
						},
						details: [
							{
								_object: '/ocean/railport',
								port_code: '3002',
							},
							{
								_object: '/trucking/port',
								port_code: '3002',
							},
							{
								_object: '/ocean/port',
								port_code: '3002',
							},
						],
					},
					terminal: null,
				},
				destination: {
					_object: '/shipment_node',
					tags: ['destination_address'],
					place: {
						_object: '/place',
						name: 'Flexport HQ',
						address: {
							_object: '/address',
							street_address: '760 Market St Fl 8',
							street_address2: null,
							city: 'San Francisco',
							state: 'CA',
							country: 'United States',
							country_code: 'US',
							zip: '94103',
							unlocode: null,
							timezone: 'America/Los_Angeles',
							ref: 'id-203333',
						},
						details: [],
					},
					terminal: null,
				},
				transportation_mode: 'truck',
				carrier_name: null,
				ocean_leg: null,
				air_leg: null,
				trucking_leg: {
					_object: '/trucking/shipment_leg',
					tracking_number: null,
					service_type: 'drayage',
					pieces: null,
					container_legs: {
						_object: '/api/refs/collection',
						ref_type: '/ocean/shipment_container_leg',
						link:
							'https://api.flexport.com/ocean/shipment_container_legs?f.leg.id=6468174',
					},
				},
				rail_leg: null,
			},
			{
				_object: '/shipment_leg',
				id: 6614900,
				shipment: {
					_object: '/api/refs/object',
					ref_type: '/shipment',
					link: 'https://api.flexport.com/shipments/719185',
					id: 719185,
				},
				estimated_arrival_date: '2020-03-26T12:00:00.000-07:00',
				actual_arrival_date: null,
				estimated_departure_date: '2020-03-12T12:00:00.000+08:00',
				actual_departure_date: '2020-03-02T12:00:00.000+08:00',
				cargo_ready_date: null,
				additional_dates: {},
				origin: {
					_object: '/shipment_node',
					tags: ['port_of_loading'],
					place: {
						_object: '/place',
						name: 'Shanghai, China',
						address: {
							_object: '/address',
							street_address: null,
							street_address2: null,
							city: 'Shanghai ',
							state: null,
							country: 'China',
							country_code: 'CN',
							zip: null,
							unlocode: 'CNSHG',
							timezone: 'Asia/Shanghai',
							ref: 'id-39042',
						},
						details: [
							{
								_object: '/trucking/port',
								port_code: '57035',
							},
							{
								_object: '/ocean/port',
								port_code: '57035',
							},
						],
					},
					terminal: null,
				},
				destination: {
					_object: '/shipment_node',
					tags: ['port_of_unloading', 'customs_entry', 'fmc_port_of_unloading'],
					place: {
						_object: '/place',
						name: 'Tacoma',
						address: {
							_object: '/address',
							street_address: null,
							street_address2: null,
							city: 'Tacoma',
							state: 'WA',
							country: 'United States',
							country_code: 'US',
							zip: null,
							unlocode: 'USTIW',
							timezone: 'America/Los_Angeles',
							ref: 'id-36164',
						},
						details: [
							{
								_object: '/ocean/railport',
								port_code: '3002',
							},
							{
								_object: '/trucking/port',
								port_code: '3002',
							},
							{
								_object: '/ocean/port',
								port_code: '3002',
							},
						],
					},
					terminal: null,
				},
				transportation_mode: 'ocean',
				carrier_name: 'Atlantic Container Line',
				ocean_leg: {
					_object: '/ocean/shipment_leg',
					scac_code: 'ACLU',
					vessel_name: 'ATLANTIC SEA',
					vessel_imo: '9670597',
					voyage_number: '1001',
					container_legs: {
						_object: '/api/refs/collection',
						ref_type: '/ocean/shipment_container_leg',
						link:
							'https://api.flexport.com/ocean/shipment_container_legs?f.leg.id=6614900',
					},
				},
				air_leg: null,
				trucking_leg: null,
				rail_leg: null,
			},
		],
	},
	error: null,
}
