module.exports = {
	_object: '/api/response',
	self: 'https://api.flexport.com/shipment_legs?f.shipment.id=35217',
	version: 2,
	data: {
		_object: '/api/collections/paginated',
		prev: null,
		next: null,
		total_count: 3,
		data: [
			{
				_object: '/shipment_leg',
				id: 795268,
				shipment: {
					_object: '/api/refs/object',
					ref_type: '/shipment',
					link: 'https://api.flexport.com/shipments/35217',
					id: 35217,
				},
				estimated_arrival_date: null,
				actual_arrival_date: null,
				estimated_departure_date: null,
				actual_departure_date: null,
				cargo_ready_date: null,
				additional_dates: {},
				origin: {
					_object: '/shipment_node',
					tags: ['port_of_loading'],
					place: {
						_object: '/place',
						name: 'Yantian, China',
						address: {
							_object: '/address',
							street_address: null,
							street_address2: null,
							city: 'Yantian',
							state: null,
							country: 'China',
							country_code: 'CN',
							zip: null,
							unlocode: 'CNYTN',
							timezone: 'Asia/Hong_Kong',
							ref: 'id-38385',
						},
						details: [
							{
								_object: '/trucking/port',
								port_code: '57078',
							},
							{
								_object: '/ocean/port',
								port_code: '57078',
							},
						],
					},
					terminal: null,
				},
				destination: {
					_object: '/shipment_node',
					tags: ['port_of_unloading', 'customs_entry'],
					place: {
						_object: '/place',
						name: 'Oakland, CA',
						address: {
							_object: '/address',
							street_address: null,
							street_address2: null,
							city: 'Oakland',
							state: 'CA',
							country: 'United States',
							country_code: 'US',
							zip: null,
							unlocode: 'USOAK',
							timezone: 'America/Los_Angeles',
							ref: 'id-41584',
						},
						details: [
							{
								_object: '/ocean/railport',
								port_code: '2811',
							},
							{
								_object: '/trucking/port',
								port_code: '2811',
							},
							{
								_object: '/ocean/port',
								port_code: '2811',
							},
						],
					},
					terminal: null,
				},
				transportation_mode: 'air',
				carrier_name: 'UASC',
				ocean_leg: null,
				air_leg: {
					_object: '/air/shipment_leg',
					iata_code: null,
					icao_code: null,
					flight_number: null,
					pieces: null,
				},
				trucking_leg: null,
				rail_leg: null,
			},
			{
				_object: '/shipment_leg',
				id: 795269,
				shipment: {
					_object: '/api/refs/object',
					ref_type: '/shipment',
					link: 'https://api.flexport.com/shipments/35217',
					id: 35217,
				},
				estimated_arrival_date: null,
				actual_arrival_date: null,
				estimated_departure_date: null,
				actual_departure_date: null,
				cargo_ready_date: '2019-11-12',
				additional_dates: {
					cargo_ready_date: '2019-11-12',
				},
				origin: {
					_object: '/shipment_node',
					tags: ['origin_address'],
					place: {
						_object: '/place',
						name: 'Queens Rd Location',
						address: {
							_object: '/address',
							street_address: "265, Queen's road west",
							street_address2: null,
							city: 'Hong Kong',
							state: null,
							country: 'Hong Kong',
							country_code: 'HK',
							zip: null,
							unlocode: null,
							timezone: 'Asia/Hong_Kong',
							ref: 'id-81218',
						},
						details: [],
					},
					terminal: null,
				},
				destination: {
					_object: '/shipment_node',
					tags: ['port_of_loading'],
					place: {
						_object: '/place',
						name: 'Yantian, China',
						address: {
							_object: '/address',
							street_address: null,
							street_address2: null,
							city: 'Yantian',
							state: null,
							country: 'China',
							country_code: 'CN',
							zip: null,
							unlocode: 'CNYTN',
							timezone: 'Asia/Hong_Kong',
							ref: 'id-38385',
						},
						details: [
							{
								_object: '/trucking/port',
								port_code: '57078',
							},
							{
								_object: '/ocean/port',
								port_code: '57078',
							},
						],
					},
					terminal: null,
				},
				transportation_mode: 'truck',
				carrier_name: 'AllStar Freight Company',
				ocean_leg: null,
				air_leg: null,
				trucking_leg: {
					_object: '/trucking/shipment_leg',
					tracking_number: null,
					service_type: 'drayage',
					pieces: null,
					container_legs: {
						_object: '/api/refs/collection',
						ref_type: '/ocean/shipment_container_leg',
						link:
							'https://api.flexport.com/ocean/shipment_container_legs?f.leg.id=795269',
					},
				},
				rail_leg: null,
			},
			{
				_object: '/shipment_leg',
				id: 795270,
				shipment: {
					_object: '/api/refs/object',
					ref_type: '/shipment',
					link: 'https://api.flexport.com/shipments/35217',
					id: 35217,
				},
				estimated_arrival_date: null,
				actual_arrival_date: null,
				estimated_departure_date: null,
				actual_departure_date: null,
				cargo_ready_date: null,
				additional_dates: {},
				origin: {
					_object: '/shipment_node',
					tags: ['port_of_unloading', 'customs_entry'],
					place: {
						_object: '/place',
						name: 'Oakland, CA',
						address: {
							_object: '/address',
							street_address: null,
							street_address2: null,
							city: 'Oakland',
							state: 'CA',
							country: 'United States',
							country_code: 'US',
							zip: null,
							unlocode: 'USOAK',
							timezone: 'America/Los_Angeles',
							ref: 'id-41584',
						},
						details: [
							{
								_object: '/ocean/railport',
								port_code: '2811',
							},
							{
								_object: '/trucking/port',
								port_code: '2811',
							},
							{
								_object: '/ocean/port',
								port_code: '2811',
							},
						],
					},
					terminal: null,
				},
				destination: {
					_object: '/shipment_node',
					tags: ['destination_address', 'deconsolidation'],
					place: {
						_object: '/place',
						name: 'Five Star New York Warehouse',
						address: {
							_object: '/address',
							street_address: '14909 183RD ST',
							street_address2: null,
							city: 'SPRINGFIELD GARDENS',
							state: 'NY',
							country: 'United States',
							country_code: 'US',
							zip: '11413',
							unlocode: 'USASA',
							timezone: 'America/New_York',
							ref: 'id-293557',
						},
						details: [],
					},
					terminal: null,
				},
				transportation_mode: 'truck',
				carrier_name: null,
				ocean_leg: null,
				air_leg: null,
				trucking_leg: {
					_object: '/trucking/shipment_leg',
					tracking_number: null,
					service_type: 'drayage',
					pieces: null,
					container_legs: {
						_object: '/api/refs/collection',
						ref_type: '/ocean/shipment_container_leg',
						link:
							'https://api.flexport.com/ocean/shipment_container_legs?f.leg.id=795270',
					},
				},
				rail_leg: null,
			},
		],
	},
	error: null,
}
