module.exports = {
	_object: '/api/response',
	self: 'https://api.flexport.com/shipment_legs?f.shipment.id=742030',
	version: 2,
	data: {
		_object: '/api/collections/paginated',
		prev: null,
		next: null,
		total_count: 5,
		data: [
			{
				_object: '/shipment_leg',
				id: 6667057,
				shipment: {
					_object: '/api/refs/object',
					ref_type: '/shipment',
					link: 'https://api.flexport.com/shipments/742030',
					id: 742030,
				},
				estimated_arrival_date: '2020-03-11T12:00:00.000+08:00',
				actual_arrival_date: '2020-03-11T12:00:00.000+08:00',
				estimated_departure_date: '2020-03-11T12:00:00.000+08:00',
				actual_departure_date: '2020-03-11T12:00:00.000+08:00',
				cargo_ready_date: '2020-03-09',
				additional_dates: {
					cargo_ready_date: '2020-03-09',
					delivery_appointment_scheduled_for_date:
						'2020-03-11T12:00:00.000+08:00',
					delivery_completed: '2020-03-11T12:00:00.000+08:00',
				},
				origin: {
					_object: '/shipment_node',
					tags: ['origin_address'],
					place: {
						_object: '/place',
						name: 'Mirko Yantian Warehouse',
						address: {
							_object: '/address',
							street_address: '3435 Shenzhen Rd.',
							street_address2: '',
							city: 'Shenzhen',
							state: 'Guangdong',
							country: 'China',
							country_code: 'CN',
							zip: null,
							unlocode: null,
							timezone: 'Asia/Shanghai',
							ref: 'id-162815',
						},
						details: [],
					},
					terminal: null,
				},
				destination: {
					_object: '/shipment_node',
					tags: ['consolidation'],
					place: {
						_object: '/place',
						name: 'SZ Test WHS',
						address: {
							_object: '/address',
							street_address: 'Modern Logistics Center',
							street_address2: 'Yantian Port Area',
							city: 'Yantian',
							state: 'Guangdong',
							country: 'China',
							country_code: 'CN',
							zip: null,
							unlocode: null,
							timezone: 'Asia/Hong_Kong',
							ref: 'id-273451',
						},
						details: [],
					},
					terminal: null,
				},
				transportation_mode: 'truck',
				carrier_name: null,
				ocean_leg: null,
				air_leg: null,
				trucking_leg: {
					_object: '/trucking/shipment_leg',
					tracking_number: null,
					service_type: 'ltl',
					pieces: null,
					container_legs: null,
				},
				rail_leg: null,
			},
			{
				_object: '/shipment_leg',
				id: 6667058,
				shipment: {
					_object: '/api/refs/object',
					ref_type: '/shipment',
					link: 'https://api.flexport.com/shipments/742030',
					id: 742030,
				},
				estimated_arrival_date: null,
				actual_arrival_date: null,
				estimated_departure_date: null,
				actual_departure_date: null,
				cargo_ready_date: null,
				additional_dates: {},
				origin: {
					_object: '/shipment_node',
					tags: ['deconsolidation'],
					place: {
						_object: '/place',
						name: 'Flexport Los Angeles Warehouse',
						address: {
							_object: '/address',
							street_address: '1420 N MCKINLEY AVE',
							street_address2: null,
							city: 'LOS ANGELES',
							state: 'CA',
							country: 'United States',
							country_code: 'US',
							zip: '90059',
							unlocode: null,
							timezone: 'America/Los_Angeles',
							ref: 'id-227012',
						},
						details: [],
					},
					terminal: null,
				},
				destination: {
					_object: '/shipment_node',
					tags: ['destination_address'],
					place: {
						_object: '/place',
						name: 'Nevada DC',
						address: {
							_object: '/address',
							street_address: '25 Industrial Way',
							street_address2: 'Building 4',
							city: 'Sparks',
							state: 'Nevada',
							country: 'United States',
							country_code: 'US',
							zip: '89431',
							unlocode: null,
							timezone: 'America/Los_Angeles',
							ref: 'id-239359',
						},
						details: [],
					},
					terminal: null,
				},
				transportation_mode: 'truck',
				carrier_name: 'Cal Sierra Express',
				ocean_leg: null,
				air_leg: null,
				trucking_leg: {
					_object: '/trucking/shipment_leg',
					tracking_number: null,
					service_type: 'ltl',
					pieces: null,
					container_legs: null,
				},
				rail_leg: null,
			},
			{
				_object: '/shipment_leg',
				id: 6667137,
				shipment: {
					_object: '/api/refs/object',
					ref_type: '/shipment',
					link: 'https://api.flexport.com/shipments/742030',
					id: 742030,
				},
				estimated_arrival_date: '2020-03-17T12:00:00.000+08:00',
				actual_arrival_date: null,
				estimated_departure_date: '2020-03-17T12:00:00.000+08:00',
				actual_departure_date: null,
				cargo_ready_date: null,
				additional_dates: {},
				origin: {
					_object: '/shipment_node',
					tags: ['consolidation'],
					place: {
						_object: '/place',
						name: 'SZ Test WHS',
						address: {
							_object: '/address',
							street_address: 'Modern Logistics Center',
							street_address2: 'Yantian Port Area',
							city: 'Yantian',
							state: 'Guangdong',
							country: 'China',
							country_code: 'CN',
							zip: null,
							unlocode: null,
							timezone: 'Asia/Hong_Kong',
							ref: 'id-273451',
						},
						details: [],
					},
					terminal: null,
				},
				destination: {
					_object: '/shipment_node',
					tags: ['port_of_loading'],
					place: {
						_object: '/place',
						name: 'Yantian, China',
						address: {
							_object: '/address',
							street_address: null,
							street_address2: null,
							city: 'Yantian',
							state: null,
							country: 'China',
							country_code: 'CN',
							zip: null,
							unlocode: 'CNYTN',
							timezone: 'Asia/Hong_Kong',
							ref: 'id-38385',
						},
						details: [
							{
								_object: '/trucking/port',
								port_code: '57078',
							},
							{
								_object: '/ocean/port',
								port_code: '57078',
							},
						],
					},
					terminal: null,
				},
				transportation_mode: 'truck',
				carrier_name: null,
				ocean_leg: null,
				air_leg: null,
				trucking_leg: {
					_object: '/trucking/shipment_leg',
					tracking_number: null,
					service_type: 'drayage',
					pieces: null,
					container_legs: {
						_object: '/api/refs/collection',
						ref_type: '/ocean/shipment_container_leg',
						link:
							'https://api.flexport.com/ocean/shipment_container_legs?f.leg.id=6667137',
					},
				},
				rail_leg: null,
			},
			{
				_object: '/shipment_leg',
				id: 6667139,
				shipment: {
					_object: '/api/refs/object',
					ref_type: '/shipment',
					link: 'https://api.flexport.com/shipments/742030',
					id: 742030,
				},
				estimated_arrival_date: '2020-04-13T12:00:00.000-07:00',
				actual_arrival_date: null,
				estimated_departure_date: '2020-04-10T12:00:00.000-07:00',
				actual_departure_date: null,
				cargo_ready_date: null,
				additional_dates: {},
				origin: {
					_object: '/shipment_node',
					tags: ['port_of_unloading', 'customs_entry', 'fmc_port_of_unloading'],
					place: {
						_object: '/place',
						name: 'Los Angeles, CA',
						address: {
							_object: '/address',
							street_address: null,
							street_address2: null,
							city: 'Los Angeles',
							state: 'CA',
							country: 'United States',
							country_code: 'US',
							zip: null,
							unlocode: 'USLAX',
							timezone: 'America/Los_Angeles',
							ref: 'id-41538',
						},
						details: [
							{
								_object: '/ocean/railport',
								port_code: '2704',
							},
							{
								_object: '/trucking/port',
								port_code: '2704',
							},
							{
								_object: '/ocean/port',
								port_code: '2704',
							},
						],
					},
					terminal: null,
				},
				destination: {
					_object: '/shipment_node',
					tags: ['deconsolidation'],
					place: {
						_object: '/place',
						name: 'Flexport Los Angeles Warehouse',
						address: {
							_object: '/address',
							street_address: '1420 N MCKINLEY AVE',
							street_address2: null,
							city: 'LOS ANGELES',
							state: 'CA',
							country: 'United States',
							country_code: 'US',
							zip: '90059',
							unlocode: null,
							timezone: 'America/Los_Angeles',
							ref: 'id-227012',
						},
						details: [],
					},
					terminal: null,
				},
				transportation_mode: 'truck',
				carrier_name: null,
				ocean_leg: null,
				air_leg: null,
				trucking_leg: {
					_object: '/trucking/shipment_leg',
					tracking_number: null,
					service_type: 'drayage',
					pieces: null,
					container_legs: {
						_object: '/api/refs/collection',
						ref_type: '/ocean/shipment_container_leg',
						link:
							'https://api.flexport.com/ocean/shipment_container_legs?f.leg.id=6667139',
					},
				},
				rail_leg: null,
			},
			{
				_object: '/shipment_leg',
				id: 6667145,
				shipment: {
					_object: '/api/refs/object',
					ref_type: '/shipment',
					link: 'https://api.flexport.com/shipments/742030',
					id: 742030,
				},
				estimated_arrival_date: '2020-04-05T18:00:00.000-07:00',
				actual_arrival_date: '2020-04-05T12:00:00.000-07:00',
				estimated_departure_date: '2020-03-20T12:00:00.000+08:00',
				actual_departure_date: '2020-03-21T08:57:24.000+08:00',
				cargo_ready_date: null,
				additional_dates: {},
				origin: {
					_object: '/shipment_node',
					tags: ['port_of_loading'],
					place: {
						_object: '/place',
						name: 'Yantian, China',
						address: {
							_object: '/address',
							street_address: null,
							street_address2: null,
							city: 'Yantian',
							state: null,
							country: 'China',
							country_code: 'CN',
							zip: null,
							unlocode: 'CNYTN',
							timezone: 'Asia/Hong_Kong',
							ref: 'id-38385',
						},
						details: [
							{
								_object: '/trucking/port',
								port_code: '57078',
							},
							{
								_object: '/ocean/port',
								port_code: '57078',
							},
						],
					},
					terminal: null,
				},
				destination: {
					_object: '/shipment_node',
					tags: ['port_of_unloading', 'customs_entry', 'fmc_port_of_unloading'],
					place: {
						_object: '/place',
						name: 'Los Angeles, CA',
						address: {
							_object: '/address',
							street_address: null,
							street_address2: null,
							city: 'Los Angeles',
							state: 'CA',
							country: 'United States',
							country_code: 'US',
							zip: null,
							unlocode: 'USLAX',
							timezone: 'America/Los_Angeles',
							ref: 'id-41538',
						},
						details: [
							{
								_object: '/ocean/railport',
								port_code: '2704',
							},
							{
								_object: '/trucking/port',
								port_code: '2704',
							},
							{
								_object: '/ocean/port',
								port_code: '2704',
							},
						],
					},
					terminal: null,
				},
				transportation_mode: 'ocean',
				carrier_name: 'APL',
				ocean_leg: {
					_object: '/ocean/shipment_leg',
					scac_code: 'APLU',
					vessel_name: 'CMA CGM G. WASHINGTON',
					vessel_imo: '9780847',
					voyage_number: '0TX5HE1PL',
					container_legs: {
						_object: '/api/refs/collection',
						ref_type: '/ocean/shipment_container_leg',
						link:
							'https://api.flexport.com/ocean/shipment_container_legs?f.leg.id=6667145',
					},
				},
				air_leg: null,
				trucking_leg: null,
				rail_leg: null,
			},
		],
	},
	error: null,
}
