module.exports = {
	_object: '/api/response',
	self: 'https://api.flexport.com/shipment_legs?f.shipment.id=561255',
	version: 2,
	data: {
		_object: '/api/collections/paginated',
		prev: null,
		next: null,
		total_count: 3,
		data: [
			{
				_object: '/shipment_leg',
				id: 5041227,
				shipment: {
					_object: '/api/refs/object',
					ref_type: '/shipment',
					link: 'https://api.flexport.com/shipments/561255',
					id: 561255,
				},
				estimated_arrival_date: '2019-07-03T12:00:00.000+08:00',
				actual_arrival_date: null,
				estimated_departure_date: '2019-07-03T12:00:00.000+08:00',
				actual_departure_date: '2019-07-03T07:00:00.000+08:00',
				cargo_ready_date: '2019-06-27',
				additional_dates: {
					cargo_ready_date: '2019-06-27',
					delivery_appointment_scheduled_for_date:
						'2019-07-03T12:00:00.000+08:00',
				},
				origin: {
					_object: '/shipment_node',
					tags: ['origin_address', 'consolidation'],
					place: {
						_object: '/place',
						name: 'Flexport Shenzhen Warehouse',
						address: {
							_object: '/address',
							street_address:
								"GLP Logistics Park, Phase II, Block 9, Mingzhu 3rd Rd and Yong'an North 2nd St",
							street_address2:
								'深圳市盐田区永安路北一街盐田港普洛斯物流园二期9号仓库',
							city: 'Shenzhen',
							state: 'Guangdong',
							country: 'China',
							country_code: 'CN',
							zip: null,
							unlocode: null,
							timezone: 'Asia/Shanghai',
							ref: 'id-160816',
						},
						details: [],
					},
					terminal: null,
				},
				destination: {
					_object: '/shipment_node',
					tags: ['port_of_loading'],
					place: {
						_object: '/place',
						name: 'Yantian, China',
						address: {
							_object: '/address',
							street_address: null,
							street_address2: null,
							city: 'Yantian',
							state: null,
							country: 'China',
							country_code: 'CN',
							zip: null,
							unlocode: 'CNYTN',
							timezone: 'Asia/Hong_Kong',
							ref: 'id-38385',
						},
						details: [
							{
								_object: '/trucking/port',
								port_code: '57078',
							},
							{
								_object: '/ocean/port',
								port_code: '57078',
							},
						],
					},
					terminal: null,
				},
				transportation_mode: 'truck',
				carrier_name: null,
				ocean_leg: null,
				air_leg: null,
				trucking_leg: {
					_object: '/trucking/shipment_leg',
					tracking_number: null,
					service_type: 'drayage',
					pieces: null,
					container_legs: {
						_object: '/api/refs/collection',
						ref_type: '/ocean/shipment_container_leg',
						link:
							'https://api.flexport.com/ocean/shipment_container_legs?f.leg.id=5041227',
					},
				},
				rail_leg: null,
			},
			{
				_object: '/shipment_leg',
				id: 5041228,
				shipment: {
					_object: '/api/refs/object',
					ref_type: '/shipment',
					link: 'https://api.flexport.com/shipments/561255',
					id: 561255,
				},
				estimated_arrival_date: '2019-08-12T12:00:00.000-04:00',
				actual_arrival_date: null,
				estimated_departure_date: '2019-08-09T12:00:00.000-04:00',
				actual_departure_date: null,
				cargo_ready_date: null,
				additional_dates: {},
				origin: {
					_object: '/shipment_node',
					tags: ['port_of_unloading', 'customs_entry', 'fmc_port_of_unloading'],
					place: {
						_object: '/place',
						name: 'New York, NY / Newark, NJ',
						address: {
							_object: '/address',
							street_address: null,
							street_address2: null,
							city: 'Newark',
							state: 'NJ',
							country: 'United States',
							country_code: 'US',
							zip: null,
							unlocode: 'USNYC',
							timezone: 'America/New_York',
							ref: 'id-41601',
						},
						details: [
							{
								_object: '/ocean/railport',
								port_code: '4601',
							},
							{
								_object: '/trucking/port',
								port_code: '4601',
							},
							{
								_object: '/ocean/port',
								port_code: '4601',
							},
						],
					},
					terminal: null,
				},
				destination: {
					_object: '/shipment_node',
					tags: ['destination_address'],
					place: {
						_object: '/place',
						name: 'CVG1',
						address: {
							_object: '/address',
							street_address: '1155 Worldwide Blvd.',
							street_address2: null,
							city: 'Hebron',
							state: 'KY',
							country: 'United States',
							country_code: 'US',
							zip: '41048',
							unlocode: null,
							timezone: 'America/New_York',
							ref: 'id-22003',
						},
						details: [],
					},
					terminal: null,
				},
				transportation_mode: 'truck',
				carrier_name: null,
				ocean_leg: null,
				air_leg: null,
				trucking_leg: {
					_object: '/trucking/shipment_leg',
					tracking_number: null,
					service_type: 'drayage',
					pieces: null,
					container_legs: {
						_object: '/api/refs/collection',
						ref_type: '/ocean/shipment_container_leg',
						link:
							'https://api.flexport.com/ocean/shipment_container_legs?f.leg.id=5041228',
					},
				},
				rail_leg: null,
			},
			{
				_object: '/shipment_leg',
				id: 5041324,
				shipment: {
					_object: '/api/refs/object',
					ref_type: '/shipment',
					link: 'https://api.flexport.com/shipments/561255',
					id: 561255,
				},
				estimated_arrival_date: '2019-08-06T12:00:00.000-04:00',
				actual_arrival_date: null,
				estimated_departure_date: '2019-07-07T12:00:00.000+08:00',
				actual_departure_date: null,
				cargo_ready_date: null,
				additional_dates: {},
				origin: {
					_object: '/shipment_node',
					tags: ['port_of_loading'],
					place: {
						_object: '/place',
						name: 'Yantian, China',
						address: {
							_object: '/address',
							street_address: null,
							street_address2: null,
							city: 'Yantian',
							state: null,
							country: 'China',
							country_code: 'CN',
							zip: null,
							unlocode: 'CNYTN',
							timezone: 'Asia/Hong_Kong',
							ref: 'id-38385',
						},
						details: [
							{
								_object: '/trucking/port',
								port_code: '57078',
							},
							{
								_object: '/ocean/port',
								port_code: '57078',
							},
						],
					},
					terminal: null,
				},
				destination: {
					_object: '/shipment_node',
					tags: ['port_of_unloading', 'customs_entry', 'fmc_port_of_unloading'],
					place: {
						_object: '/place',
						name: 'New York, NY / Newark, NJ',
						address: {
							_object: '/address',
							street_address: null,
							street_address2: null,
							city: 'Newark',
							state: 'NJ',
							country: 'United States',
							country_code: 'US',
							zip: null,
							unlocode: 'USNYC',
							timezone: 'America/New_York',
							ref: 'id-41601',
						},
						details: [
							{
								_object: '/ocean/railport',
								port_code: '4601',
							},
							{
								_object: '/trucking/port',
								port_code: '4601',
							},
							{
								_object: '/ocean/port',
								port_code: '4601',
							},
						],
					},
					terminal: null,
				},
				transportation_mode: 'ocean',
				carrier_name: null,
				ocean_leg: {
					_object: '/ocean/shipment_leg',
					scac_code: null,
					vessel_name: null,
					vessel_imo: null,
					voyage_number: null,
					container_legs: {
						_object: '/api/refs/collection',
						ref_type: '/ocean/shipment_container_leg',
						link:
							'https://api.flexport.com/ocean/shipment_container_legs?f.leg.id=5041324',
					},
				},
				air_leg: null,
				trucking_leg: null,
				rail_leg: null,
			},
		],
	},
	error: null,
}
